name: Build Release APK
on:
  push:
    branches:
      - main # change this to your app's main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: 3.7.5

    - name: Get dependencies
      run: flutter pub get

    - name: Build release APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-app-release
        path: build/app/outputs/flutter-apk/app-release.apk
