name: Build Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Flutter manually
      run: |
        curl -o flutter.tar.xz https://storage.googleapis.com/flutter_infra/releases/stable/mac/flutter_macos_3.7.5-stable.tar.xz
        tar xf flutter.tar.xz
        export PATH="$PATH:`pwd`/flutter/bin"

    - name: Get dependencies
      run: flutter pub get

    - name: Build release APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-app-release
        path: build/app/outputs/flutter-apk/app-release.apk
